### ISSUE TITLE
Can't init new project

### ISSUE THREAD

**Issue by semencov** [tamiadev/generator-tamia#2]
Both `yo tamia` and `yo tapia:init` abort with this message:

``` bash
✖ Generator config not found. Please run yo tamia:init.
```

Is there any prerequisites?

---

generator-tamia v0.1.0
Yeoman v1.4.6
NPM v2.7.3
Node.js v0.12.0

**Comment by sapegin** [comment]
There’s a bug that’s already fixed in master. I’ll publish new version to npm.

**Comment by sapegin** [comment]
Done.
